sudo: required
services:
  - docker
before_install:
  - docker build -t fyang123\darker -f Dockerfile.dev .


language: generic
script: 
  - docker run -e CI=true fyang123\docker npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker"
#   evn: "docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-#######"
#   bucket_path: "docker"
# on:
#    branch: master
   